src/main/forms/__init__.py
from .comments import CommentForm, ReplyForm
from .auth import LoginForm, RegisterForm
from .admin import CategoryForm, BannerForm

src/main/config/__init__.py
# from .app import app

import datetime
from pathlib import Path

from flask import Flask, render_template
from flask_cors import CORS
from flask_debugtoolbar import DebugToolbarExtension

from src.config import app_config

from src.infra.tutorial3 import Category, Setting, Permission, Roles, Department

## Path.cwd()는 실행파일(root의 run.py)의 위치가 찍힌다 -> root부터 경로잡기
# -> path는 joinpath시 끝이 디렉토리라면 / 까지 넣어줘야한다.
from src.main.init_script import init_script
from src.main.utils.format_date import format_date, format_datetime, format_timedelta

template_dir = str(Path.cwd().joinpath('src/main/templates/'))
static_dir = str(Path.cwd().joinpath('src/main/static/'))
print(f"template_dir: {template_dir}\n"
      f"static_dir: {static_dir}")


## 추가 extenstion객체 생성
# migrate = Migrate()
# moment = Moment()
# pagedown = PageDown()


def create_app(config_name='default'):
    app = Flask(__name__,
                template_folder=template_dir,
                static_folder=static_dir,
                )

    ## db환경변수를 개별로 넣지않고 config object로 넣는다.
    # app.config["SECRET_KEY"] = app_config.SECRET_KEY
    # app_config.init_app(app)
    app.config.from_object(app_config)


    ## extension객체들로 app객체 초기화
    CORS(app)
    DebugToolbarExtension(app)
    app.config['DEBUG_TB_INTERCEPT_REDIRECTS'] = False

    ## 필터 추가
    from src.main.templates.filters import feed_datetime, join_phone, join_birth
    app.jinja_env.filters["feed_datetime"] = feed_datetime
    app.jinja_env.filters["join_phone"] = join_phone
    app.jinja_env.filters["join_birth"] = join_birth
    app.jinja_env.filters["format_date"] = format_date
    app.jinja_env.filters["format_datetime"] = format_datetime
    app.jinja_env.filters["format_timedelta"] = format_timedelta

    ## bp아닌 것들은 add_url_rule용
    from src.main.routes import (
        main_bp, index,
        api_routes_bp, auth_bp,
        admin_bp,
        util_bp,
        dept_bp,
        comment_bp,
        todo_bp,

    )

    app.register_blueprint(main_bp)
    app.register_blueprint(api_routes_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(admin_bp)
    app.register_blueprint(util_bp)
    app.register_blueprint(dept_bp)
    app.register_blueprint(comment_bp)
    app.register_blueprint(todo_bp)

    # 기본 / url 지정 in route.py의 function
    app.add_url_rule('/', endpoint='index', view_func=index)
    from ..utils.upload_utils import download_file
    app.add_url_rule('/uploads/<path:filename>', endpoint='download_file', view_func=download_file)

    ## app context단위로 항상 떠있는 entity 객체value의 dict 반환 method 주입
    app.context_processor(inject_category_and_settings)
    app.context_processor(inject_today_date)
    # app.context_processor(inject_permission_and_roles)
    app.context_processor(inject_permission)
    app.context_processor(inject_departments)

    ## [flask xxxx] 명령어 추가
    init_script(app)

    ## 오류페이지 등록
    app.register_error_handler(404, render_error)
    app.register_error_handler(500, render_error)

    return app


def inject_category_and_settings():
    categories = Category.order_by('id').all()
    settings = Setting.convert_to_dict()

    return dict(
        categories=categories,
        settings=settings,
    )

def inject_today_date():
    return {'today_date': datetime.date.today}

# def inject_permission_and_roles():
## role Roles이넘을 이용해 user객체의 hybrid_property로 다 정해줌
def inject_permission():
    return dict(
        Permission=Permission,
        # Roles=Roles,
    )

def inject_departments():
    # 나중에는 root들을 all()로 찾고 -> load1번만 한 상태로 children을 각 그룹들로 ㅟ급하자.
    # -> 각 그룹들은 dropdown으로 나타내던지 하자.
    # departments = Department.filter_by(level=1).order_by('sort').all()

    # root_department = Department.load({'children':'joined'}).filter_by(level=0).first()
    # departments = root_department.children

    root_departments = Department.load({'children':'joined'}).filter_by(level=0).all()
    # departments = root_department.children

    return dict(
        root_departments=root_departments,
        # departments=departments
    )

## 에러 핸들링
# def page_not_found(e):
def render_error(e):
    # print(dir(e))
    # 'args', 'code', 'description', 'get_body', 'get_description', 'get_headers', 'get_response', 'name', 'response', 'with_traceback', 'wrap']
    # print(e.code) # 404
    # print(e.description) # The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

    return render_template(
        'errors/http_errors.html',
        status_code=e.code,
        description=e.description), e.code

src/main/forms/admin/__init__.py
from .forms import CategoryForm, PostForm, TagForm, CreateUserForm, BannerForm

src/main/routes/__init__.py
from .api_route import api_routes_bp, menu
from .main_route import main_bp, index
from .auth_route import auth_bp
from .admin_route import admin_bp
from .util_route import util_bp
from .department_route import dept_bp
from .comment_route import comment_bp
from .todo_route import todo_bp

src/main/routes/main_route.py
import json
import random
import re
from functools import cmp_to_key

from flask import Blueprint, render_template, request, url_for, flash, redirect, g
from sqlalchemy import select, and_, extract, or_

from src.infra.config.connection import DBConnectionHandler
from src.infra.tutorial3 import Post, Category, Tag, Banner, PostPublishType, Department, Employee, Todo, TodoType
from src.infra.tutorial3.categories import PostCount, Comment
from src.infra.tutorial3.common.pagination import paginate
from src.main.decorators.decorators import login_required
from src.main.forms.admin import PostForm
from src.main.utils import redirect_url, delete_files_in_img_tag
from src.main.utils.format_date import format_date
from src.main.utils.get_client_ip import get_client_ip

main_bp = Blueprint("main", __name__, url_prefix='/main')


@main_bp.route("/")
def index():
    page = request.args.get('page', 1, type=int)

    pagination = Post.order_by('-add_date').paginate(page, per_page=9)
    post_list = pagination.items

    # 공용 이미지
    img_path_list = [f'img/post/post-{i}.jpg' for i in range(1, 15 + 1)]
    for post, img_path in zip(post_list, random.sample(img_path_list, k=len(post_list))):
        post.img = img_path

    # banner to json
    banner_list = Banner.order_by('-is_fixed', '-add_date') \
        .limit(5) \
        .all()

    # baner객체들을 img, url만 가진 dict_list로 변환
    banner_list = [{
        'img': f'{url_for("download_file", filename=banner.img)}',
        'url': banner.url,
        'desc': banner.desc,
    }
        for banner in banner_list]

    return render_template('main/index.html', post_list=post_list, pagination=pagination,
                           banner_list=banner_list)


# @main_bp.route("/")
# def index():
#     # post_list = [1, 2, 3, 4, 5, 6]
#     page = request.args.get('page', 1, type=int)
#
#     stmt = select(Post).order_by(Post.add_date.desc())
#     pagination = paginate(stmt, page=page, per_page=9)
#
#     post_list = pagination.items
#
#     # 이미 내장된 img의 경로를 db에 존재하지 않는 필드지만 동적으로 삽입
#     # -> error가능성) sample의 k보다 post가 많아지는 경우? 해당이 안될 수 있다.
#     img_path_list = [f'img/post/post-{i}.jpg' for i in range(1, 15 + 1)]
#     for post, img_path in zip(post_list, random.sample(img_path_list, k=len(post_list))):
#         post.img = img_path
#
#     ## banner to json
#     stmt = select(Banner).order_by(Banner.is_fixed.desc(), Banner.add_date.desc()) \
#         .limit(5)
#     with DBConnectionHandler() as db:
#         banner_list = db.session.scalars(stmt).all()
#     # baner객체들을 img, url만 가진 dict_list로 변환
#     banner_list = [{
#         'img': f'{url_for("download_file", filename=banner.img)}',
#         'url': banner.url,
#         'desc': banner.desc,
#
#     }
#         for banner in banner_list]
#     # json.load()로 읽어올 것이 아니라면, ensure_ascii=False를 필수로 해줘야 view에서 한글로 받을 수 있다.
#     # banner_list = json.dumps(banner_list, ensure_ascii=False)
#     #### 새로운 방법: jinja로는 dictlist를 넘긴 뒤, vue의 데이터 초기화 코드에서, "{{ dict_list | tojson }}"의 문자열 + jinja + tojson필터를 이용한다.
#     # -> app._data.banner_list = JSON.parse('{{ banner_list | tojson }}')
#
#     return render_template('main/index.html', post_list=post_list, pagination=pagination,
#                            banner_list=banner_list)


# @main_bp.route("/category/<int:id>")
# def category(id):
#     # 1. category 찾기
#     with DBConnectionHandler() as db:
#         category = db.session.get(Category, id)
#
#     # 2. 딸린 posts 찾고, pagination적용
#     page = request.args.get('page', 1, type=int)
#     stmt = (
#         select(Post)
#         .where(Post.category_id == category.id)
#         .order_by(Post.add_date.desc())
#     )
#     pagination = paginate(stmt, page=page, per_page=10)
#     post_list = pagination.items
#
#     # print(category, post_list)
#
#     # 3. category + 딸린 post_list 한꺼번에 반환
#     # 4. categories(app_menu)와 상시비교되지만 평소에는 None으로 표기안됨. 진입시만 표기되로고
#     #    category.id == category_id로 비교할 현재 category_id 넘겨주기
#     return render_template('main/category.html',
#                            category=category,
#                            post_list=post_list, pagination=pagination,
#                            category_id=category.id
#                            )

@main_bp.route("/category/<int:id>")
def category(id):
    # 상위entity인 category 자체 설명
    category = Category.get(id)

    page = request.args.get('page', 1, type=int)

    # category에 딸린 posts들
    # - 각각은 부모인 category 정보를(필터링 뿐만 아니라. post.category.name)을 사용함.
    # - 각각은 딸린 tags정보를
    pagination = Post.load({'category': 'selectin', 'tags': 'joined',
                            'author': ('selectin', {'user': 'selectin'},),
                            'comments': 'joined'  # 댓글 갯수 @h comment_count를 사용하기 위해
                            }) \
        .filter_by(
        type=PostPublishType.SHOW,
        category___id=id
    ) \
        .order_by('-add_date') \
        .paginate(page, per_page=10)

    post_list = pagination.items

    return render_template('main/category.html',
                           category=category,
                           post_list=post_list, pagination=pagination,
                           category_id=id  # base.html의 메뉴 불들어오게 하는 용도
                           )


@main_bp.route("/department/<int:id>")
@login_required
def department(id):
    department = Department.get(id)

    page = request.args.get('page', 1, type=int)

    schema = {
        'category': 'selectin', 'tags': 'joined',
        'author': ('selectin', {
            'user': 'selectin',  # employee(author name) + user(for avatar)
        },),
        'comments': 'joined'  # 댓글 갯수 @h comment_count를 사용하기 위해
    }

    # level 0 부서는 작성자의 상위부서 == level 1부서들을 post마다 나타내기용
    if department.level == 0:
        schema['author'][1].update({'upper_department': 'selectin'})

    pagination = Post.load(schema) \
        .filter_by(
        type=PostPublishType.SHOW,
        is_author_upper_department=department,  # level 0이면 내부에서 자식 level 1 부서들을 꺼내서 필터링
    ) \
        .order_by('-add_date') \
        .paginate(page, per_page=5)

    post_list = pagination.items

    return render_template('main/department.html',
                           department=department,  # post 전에 상위entity 정보 뿌리기용 ?
                           post_list=post_list,
                           pagination=pagination,
                           current_dept_id=id,  # base.html에서 메뉴 불들어오게 하는 용도
                           )


# # 1) 상위entity를 타고 들어가야하는 소속된 하위 entity의 url은 /상위entity/상위entity_id/ + /자신_id로 구성한다
# # -> 단독 entity/id는 이미 admin_route에서 가지기 때문
# @main_bp.route("/category/<int:category_id>/<int:id>")
# def post_detail(category_id, id):
#     # 2) 타고 들어가는 하위의 경우, 부모도 먼저 찾고 -> 나 찾기
#     with DBConnectionHandler() as db:
#         category = db.session.get(Category, category_id)
#         #### cateogory.posts에서  넘어온 post의 id로 post객체를 골라낼 수 있다.
#         # post = [cate_post for cate_post in  category.posts if cate_post.id == id][0]
#         # -> 하지만, lazy로 찾은 객체를 view에 넘겨서 post.title 등을 사용하면 session연결이 끊긴 객체라 뜬다.
#         # -> view에 넘겨줄 객체는 한번 더 찾자.
#         post = db.session.get(Post, id)
#
#         # 3) detail에서 이전글, 다음글을 [1]해당category안에서 [2]id작은것들 가장 큰 것(역순1번째) [2] id큰것들 중 정순 1번재를 찾으면 된다.
#         # ==> 이미 찾아놓은 category, post를 stmt로 쿼리날리면, 경고가 뜬다. 이미 .post와 post.category로 연결된 사이라고
#         # -> category.posts를 이용해서 필터링해서 이전글을 찾는다.
#         prev_posts = sorted([cate_post for cate_post in category.posts if cate_post.id < post.id],
#                             key=lambda x: x.id, reverse=True)
#         next_posts = sorted([cate_post for cate_post in category.posts if cate_post.id > post.id],
#                             key=lambda x: x.id)
#         # 필터링안걸리면 빈list로서 [0] 첫번째 객체를 indexing할 수없기 때문에 조건문으로 준다.
#         prev_post = prev_posts[0] if prev_posts else None
#         next_post = next_posts[0] if next_posts else None
#         ## sqlawarning -> 이미 lazy된 객체끼리 또 조회해서 비교한다고
#         # prev_stmt = select(Post)\
#         #     .where(and_(Category.id == post.category_id, Post.id < post.id))\
#         #     .order_by(Post.id.desc())\
#         #     .limit(1)
#         # next_stmt = select(Post)\
#         #     .where(and_(Category.id == post.category_id, Post.id > post.id))\
#         #     .order_by(Post.id.asc())\
#         #     .limit(1)
#         # prev_post = db.session.scalars(prev_stmt).first()
#         # next_post = db.session.scalars(next_stmt).first()
#
#     # print(post, prev_posts, next_posts)
#
#     return render_template('main/post_detail.html',
#                            category=category, post=post,
#                            prev_post=prev_post, next_post=next_post)
#

# 1) 상위entity를 타고 들어가야하는 소속된 하위 entity의 url은 /상위entity/상위entity_id/ + /자신_id로 구성한다
# -> 단독 entity/id는 이미 admin_route에서 가지기 때문
@main_bp.route("/category/<int:category_id>/<int:id>")
def post_detail(category_id, id):
    # 타고 들어가는 하위의 경우, 부모id -> 이전글/다음글을 찾을 수 있다.
    # post = Post.load({'category': 'selectin', 'tags': 'joined', }) \
    #     .filter_by(id=id).first()

    # post = Post.filter_by(id=id).first()

    # 조회수 먼저 처리
    ip = get_client_ip(request)
    # 해당 post에 대해 ip로 등록된 데이터를 세서, count를 나타냄
    # if 해당ip 데이터가 없을때만 등록후 조회수 + 1
    count = PostCount.filter_by(post_id=id, ip=ip).count()
    if count == 0:
        PostCount.create(post_id=id, ip=ip)
        # 조회 수 증가는 등록안된 ip(count==0)일 경우만
        # post.view_count += 1
        post = Post.get(id)
        post.update(view_count=post.view_count + 1)
        # load한 데이터가 그대로 남아있으려나? -> commit해서 없다

    # limit 이전 글의 갯수
    prev_post = Post.filter_by(
        type=PostPublishType.SHOW,
        category___id=category_id,
        id__lt=id,
    ).order_by('-id') \
        .limit(1) \
        .first()

    # limit 다음 글의 갯수
    next_post = Post.filter_by(
        type=PostPublishType.SHOW,
        category___id=category_id,
        id__gt=id,
    ).order_by('id') \
        .limit(1) \
        .first()

src/main/routes/util_route.py
from flask import request, url_for, Blueprint

from src.main.decorators.decorators import login_required
from src.main.utils import upload_file_path

util_bp = Blueprint("util", __name__, url_prefix='/util')


# upload route
# 1. POST로 FormData를 받긴 하지만, upload요청마다 '/uploads/`폴더 속 `개별디렉토리이름`은 요청마다 달라진다.
# -> POST지만, path로 directory_name을 받아서, 업로드폴더의 하위 개별폴더로 지정해서 저장하도록 한다

@util_bp.route('/upload/<path:directory_name>', methods=['POST'])
@login_required
def upload(directory_name):
    if request.method == 'POST':
        # 2. 파일객체는 new FormData()객체 속 'upload'로 append했는데
        # -> request.files.get('upload')로 받아낼 수 있다.
        f = request.files.get('upload')
        # 3. file객체를 .read()로 내용물을 읽고 file size를 젠 뒤
        # -> file객체의 읽은 위치를 다시 처음으로 초기화해놓는다.(읽고 커서가 뒤로 갔지만, 다시 원위치
        file_size = len(f.read())
        f.seek(0)
        # 4. 업로드 파일 사이즈를 체크한다. form에서는 validators= [FileSize(max_size=2048000))]으로 해결
        # -> 사이즈가 넘어가면 alert를 띄울 수있게 message를 같이 전달한다.
        if file_size > 2048000:
            return {
                'code': 'err',
                'message': '파일크기가 2M를 넘을 수 없습니다.'
            }
        # 5. upload유틸을 이용해서, '/uploads/`폴더에 붙을 '개별디렉토리', file객체를 넣어주면
        # -> save할 path와 filename이 주어진다.
        # -> 그렇다면, front에서 upload할 개별디렉토리도 보내줘야한다?!
        upload_path, filename = upload_file_path(directory_name=directory_name, file=f)
        # print(upload_path, filename)
        # C:\Users\is2js\pythonProject\2022_sqlalchemy\uploads\post\28d12f83306f4bf6984c9b6bcef7dda5.png 28d12f83306f4bf6984c9b6bcef7dda5.png

        # 6. 저장 후 ok return 시  jsonify없이 그냥 dict로 반환한다?
        # -> 반환시 view에서 볼 img저장경로를 넘겨줘야, 거기서 표시할 수 있을 것이다.
        f.save(upload_path)
        # print(url_for('download_file', filename=f'{directory_name}/{filename}'))
        # /uploads/post/862e406dd33a48b6aed55e64e68586ff.png

        return {
            'code': 'ok',
            # 'url': f'/uploads/{directory_name}/{filename}',
            'url': url_for('download_file', filename=f'{directory_name}/{filename}'),
        }

src/main/templates/filters/__init__.py
from .feed_datetime import feed_datetime
from .join_phone import join_phone, join_birth

src/main/utils/__init__.py
from .upload_utils import upload_file_path, delete_uploaded_file, delete_files_in_img_tag
from .utils import remove_empty_and_hyphen, redirect_url

src/main/templates/main/archive.html
{% extends 'main/category.html' %}

{% block title %} {{ date }} Archive {% endblock title %}

{% block hero %}{% endblock hero %}

{% block breadcrumb %}
<nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
        <li><a href="/">Home</a></li>
        <li class="is-active">
            <a href="#" aria-current="page"> {{ date }}</a>
        </li>
    </ul>
</nav>
{% endblock breadcrumb %}


{% block pagination %}
<nav class="pagination is-small" role="navigation" aria-label="pagination">
    {% if pagination.has_prev %}
    <a href="{{ url_for('main.archive', date=date ) }}?page={{ pagination.prev_num }}" class="pagination-previous"
       title="This is the first page">Previous</a>
    {% endif %}
    {% if pagination.has_next %}
    <a href="{{ url_for('main.archive', date=date) }}?page={{ pagination.next_num }}" class="pagination-next">Next
        page</a>
    {% endif %}

    <ul class="pagination-list">
        {% for page in pagination.iter_pages() %}
        {% if page %}
        {% if page != pagination.page %}
        <li>
            <a href="{{ url_for('main.archive', date=date) }}?page={{ page }}" class="pagination-link"
               aria-label="Page 1" aria-current="page">{{ page }}</a>
        </li>
        {% else %}
        <li>
            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
        </li>
        {% endif %}
        {% else %}
        <span class=pagination-ellipsis>&hellip;</span>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endblock pagination %}

src/main/templates/main/category.html
{% extends 'base.html' %}

{% block title %} {{ category.name }} {% endblock title %}

{% block hero %}{% endblock hero %}

{% block box %}
<div class="columns">
    <div class="column is-9" style="border-right:solid 1px #eee ;">
        <div class="box is-shadowless has-background-light">
            <!-- new breadcrumb block  -->
            {% block breadcrumb %}
            <nav class="breadcrumb is-small" aria-label="breadcrumbs">
                <ul>
                    <!-- Home만 addrule /로 직접 걸어주고 -->
                    <li><a href="/">Home</a></li>
                    <!-- 이후로는 직접 객체로 걸어주는데, [현재]면 #으로 걸고, .name만 / [부모]도 껴있으면 부모객체 -->
                    <li class="is-active">
                        <a href="#" aria-current="page">{{ category.name }}</a>
                    </li>
                </ul>
            </nav>
            {% endblock breadcrumb %}
        </div>

        <!-- new 해당domain_box block 안에서 하위들을 돌린다. -->
        {% block cate_box %}
        {% for post in post_list %}
        <div class="pl-2">
            <!-- [좌측정렬] 프로필 | 이름 | 시간 -->
            <div class="is-pulled-left">
                <div class="has-text-grey-light is-size-7 mt-1 is-align-items-center is-flex">
                    <figure class="image  mr-2 is-inline-block" style="border: none;">
                        <img class="is-rounded" style="height: 30px; width: 30px;"
                             src="
                                 {% if post.author.user.avatar %}
                                 {{url_for('download_file', filename=post.author.user.avatar)}}
                                 {% else %}
                                 {{url_for('static', filename='/img/user/default_avatar.svg')}}
                                 {% endif %}
                                "
                             alt="{{ g.user.username }}">
                    </figure>
                    <span class="has-text-black has-text-weight-bold">
                        {{ post.author.name }}
                    </span>
                    <span class="icon"><i class="mdi mdi-clipboard-text-clock-outline"></i></span>{{ post.add_date |
                    feed_datetime(is_feed=True) }}
                </div>
            </div>

            <!-- [우측정렬] 조회수 + 태그 -->
            <div class="is-pulled-right mr-2">
                <div class="has-text-grey is-size-7">
                    {% if post.tags %}
                    <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{ post.tags|join(', ') }}
                    {% endif %}
                    <span class="icon"><i class="mdi mdi-eye-outline"></i></span> {{ post.view_count }}
                </div>
            </div>
            <!-- [좌우정렬 후 cleaerfix] -->
            <div class="is-clearfix"></div>

            <!-- title + desc -->
            <div class="mt-2 is-size-5 has-text-weight-bold">
                <a href="{{ url_for('main.post_detail', category_id=post.category_id, id=post.id) }}">
                    {{ post.title }}</a>
            </div>
            {% if post.desc %}
            <div class="has-text-grey is-size-7 ">설명: {{ post.desc }}</div>
            {% endif %}

            <!-- 카테고리 + 댓글 갯수 -->
            <div class="my-3 is-size-7 is-flex is-align-items-center">
                <!-- 카테고리 -->
                <span class="tag is-rounded is-{{post.category.icon}}">
                        {{ post.category.name }}
                </span>
                <!-- 댓글 갯수 -->
                {% if post.comment_count > 0 %}
                <b-button class="is-rounded has-text-grey mx-2" size="is-small" style="font-size: 0.6rem"
                >
                    <span class="icon" style="width: 20px" ><i class="mdi mdi-comment-outline"></i></span>
                    {{ post.comment_count }}
                </b-button>
                {% endif %}
            </div>

        </div>
        <div class=" dropdown-divider mb-3"></div>
        {% endfor %}

        {% block pagination %}
        <nav class="pagination is-small" role="navigation" aria-label="pagination">
            {% if pagination.has_prev %}
            <!-- 현재route를 걸어줘야한다 -->
            <a href="{{ url_for('main.category', id=cate.id ) }}?page={{ pagination.prev_num }}"
               class="pagination-previous" title="This is the first page">Previous</a>
            {% endif %}
            {% if pagination.has_next %}
            <a href="{{ url_for('main.category', id=cate.id ) }}?page={{ pagination.next_num }}"
               class="pagination-next">Next page</a>
            {% endif %}

            <ul class="pagination-list">
                {% for page in pagination.iter_pages() %}
                {% if page %}
                {% if page != pagination.page %}
                <li>
                    <a href="{{ url_for('main.category', id=cate.id) }}?page={{ page }}" class="pagination-link"
                       aria-label="Page 1" aria-current="page">{{ page }}</a>
                </li>
                {% else %}
                <li>
                    <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                </li>
                {% endif %}
                {% else %}
                <span class=pagination-ellipsis>&hellip;</span>
                {% endif %}
                {% endfor %}

            </ul>
        </nav>
        {% endblock pagination %}

        {% endblock cate_box %}
    </div>

    <!-- new html -> block아니라서 상속한 자식들은 다 공유  -->
    <div class="column">

        <!-- 검색 -->
        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-search-web"></i></span>
                검색
            </h1>
            <div class=" dropdown-divider"></div>
            <form action="{{url_for('main.search')}}" method="get">
                <div class="field has-addons">
                    <div class="control">
                        <input class="input" type="search" value="{{word}}" name="word" placeholder="검색keyword 입력">
                    </div>
                    <div class="control">
                        <input type="submit" value="Search" class="button is-info">
                    </div>
                </div>
            </form>
        </div>


        <!-- 최근게시물   -->
        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
                Recent Article
            </h1>
            <div class=" dropdown-divider"></div>
            <ul>
                {% for post in new_posts %}
                <li class="pl-2">
                    <span class=" has-text-grey-light">{{ loop.index }}.</span>
                    <a href="{{ url_for('main.post_detail', category_id=post.category_id, id=post.id) }}">
                        {{post.title}}
                    </a>
                </li>
                <div class="dropdown-divider"></div>
                {% endfor %}
            </ul>
        </div>


        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
                Archive
            </h1>
            <div class="dropdown-divider"></div>
            <!-- archive  -->
            <ul>
                {% for date in dates %}
                <li class="pl-2">
                    <a href="{{ url_for('main.archive', date=date) }}"> {{date}} </a>
                </li>
                <div class="dropdown-divider"></div>
                {% endfor %}
            </ul>
        </div>

        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-tag-multiple-outline"></i></span>
                Tag
            </h1>
            <div class=" dropdown-divider"></div>
            <!-- tag  -->
            <div class="tags">
                {% for tag in tags %}
                <a class="tag {{ tag.style | random() }}"
                   href="{{ url_for('main.tag', id=tag.id) }}">
                    {{ tag.name }}
                </a>
                {% endfor %}
            </div>
        </div>

    </div>
</div>
{% endblock box %}