src/main/forms/__init__.py
from .comments import CommentForm, ReplyForm
from .auth import LoginForm, RegisterForm
from .admin import CategoryForm, BannerForm

src/main/config/__init__.py
# from .app import app

import datetime
from pathlib import Path

from flask import Flask, render_template
from flask_cors import CORS
from flask_debugtoolbar import DebugToolbarExtension

from src.config import app_config

from src.infra.tutorial3 import Category, Setting, Permission, Roles, Department

## Path.cwd()는 실행파일(root의 run.py)의 위치가 찍힌다 -> root부터 경로잡기
# -> path는 joinpath시 끝이 디렉토리라면 / 까지 넣어줘야한다.
from src.main.init_script import init_script
from src.main.utils.format_date import format_date, format_datetime, format_timedelta

template_dir = str(Path.cwd().joinpath('src/main/templates/'))
static_dir = str(Path.cwd().joinpath('src/main/static/'))
print(f"template_dir: {template_dir}\n"
      f"static_dir: {static_dir}")


## 추가 extenstion객체 생성
# migrate = Migrate()
# moment = Moment()
# pagedown = PageDown()


def create_app(config_name='default'):
    app = Flask(__name__,
                template_folder=template_dir,
                static_folder=static_dir,
                )

    ## db환경변수를 개별로 넣지않고 config object로 넣는다.
    # app.config["SECRET_KEY"] = app_config.SECRET_KEY
    # app_config.init_app(app)
    app.config.from_object(app_config)


    ## extension객체들로 app객체 초기화
    CORS(app)
    DebugToolbarExtension(app)
    app.config['DEBUG_TB_INTERCEPT_REDIRECTS'] = False

    ## 필터 추가
    from src.main.templates.filters import feed_datetime, join_phone, join_birth
    app.jinja_env.filters["feed_datetime"] = feed_datetime
    app.jinja_env.filters["join_phone"] = join_phone
    app.jinja_env.filters["join_birth"] = join_birth
    app.jinja_env.filters["format_date"] = format_date
    app.jinja_env.filters["format_datetime"] = format_datetime
    app.jinja_env.filters["format_timedelta"] = format_timedelta

    ## bp아닌 것들은 add_url_rule용
    from src.main.routes import (
        main_bp, index,
        api_routes_bp, auth_bp,
        admin_bp,
        util_bp,
        dept_bp,
        comment_bp,
        todo_bp,

    )

    app.register_blueprint(main_bp)
    app.register_blueprint(api_routes_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(admin_bp)
    app.register_blueprint(util_bp)
    app.register_blueprint(dept_bp)
    app.register_blueprint(comment_bp)
    app.register_blueprint(todo_bp)

    # 기본 / url 지정 in route.py의 function
    app.add_url_rule('/', endpoint='index', view_func=index)
    from ..utils.upload_utils import download_file
    app.add_url_rule('/uploads/<path:filename>', endpoint='download_file', view_func=download_file)

    ## app context단위로 항상 떠있는 entity 객체value의 dict 반환 method 주입
    app.context_processor(inject_category_and_settings)
    app.context_processor(inject_today_date)
    # app.context_processor(inject_permission_and_roles)
    app.context_processor(inject_permission)
    app.context_processor(inject_departments)

    ## [flask xxxx] 명령어 추가
    init_script(app)

    ## 오류페이지 등록
    app.register_error_handler(404, render_error)
    app.register_error_handler(500, render_error)

    return app


def inject_category_and_settings():
    categories = Category.order_by('id').all()
    settings = Setting.convert_to_dict()

    return dict(
        categories=categories,
        settings=settings,
    )

def inject_today_date():
    return {'today_date': datetime.date.today}

# def inject_permission_and_roles():
## role Roles이넘을 이용해 user객체의 hybrid_property로 다 정해줌
def inject_permission():
    return dict(
        Permission=Permission,
        # Roles=Roles,
    )

def inject_departments():
    # 나중에는 root들을 all()로 찾고 -> load1번만 한 상태로 children을 각 그룹들로 ㅟ급하자.
    # -> 각 그룹들은 dropdown으로 나타내던지 하자.
    # departments = Department.filter_by(level=1).order_by('sort').all()

    # root_department = Department.load({'children':'joined'}).filter_by(level=0).first()
    # departments = root_department.children

    root_departments = Department.load({'children':'joined'}).filter_by(level=0).all()
    # departments = root_department.children

    return dict(
        root_departments=root_departments,
        # departments=departments
    )

## 에러 핸들링
# def page_not_found(e):
def render_error(e):
    # print(dir(e))
    # 'args', 'code', 'description', 'get_body', 'get_description', 'get_headers', 'get_response', 'name', 'response', 'with_traceback', 'wrap']
    # print(e.code) # 404
    # print(e.description) # The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

    return render_template(
        'errors/http_errors.html',
        status_code=e.code,
        description=e.description), e.code

src/main/forms/admin/__init__.py
from .forms import CategoryForm, PostForm, TagForm, CreateUserForm, BannerForm

src/main/routes/__init__.py
from .api_route import api_routes_bp, menu
from .main_route import main_bp, index
from .auth_route import auth_bp
from .admin_route import admin_bp
from .util_route import util_bp
from .department_route import dept_bp
from .comment_route import comment_bp
from .todo_route import todo_bp

src/main/routes/api_route.py
from pathlib import Path

from flask import Blueprint, jsonify, render_template, request, flash, url_for, redirect
from sqlalchemy import select
from sqlalchemy.orm import joinedload, selectinload, subqueryload, immediateload, aliased, lazyload
from sqlalchemy.orm.strategy_options import contains_eager

from src.config import db_config
from src.infra.commons import paginate
from src.infra.config.connection import DBConnectionHandler
from src.infra.tutorial3 import Comment, Menu
from src.main.forms import CommentForm, ReplyForm

api_routes_bp = Blueprint("api_routes", __name__)


@api_routes_bp.route("/api", methods=["GET"])
def something():
    return jsonify({"abcd": "abcd"})


@api_routes_bp.route("/explore", methods=["GET", "POST"])
def explore():
    comment_form = CommentForm()
    reply_form = ReplyForm()

    with DBConnectionHandler() as db:
        stmt = (
            select(Comment)
            .options(lazyload('*'))  # 현재 lazy="subquery"y로 되어있기 때문에, jinja용 path이용한다면, 다 가져올 필요없음. flat 조회
            .order_by(Comment.thread_timestamp.desc(), Comment.path.asc(), Comment.id.asc())
        )

        # select()객체, execute(), scalars()모두 paginate()메서드가 없음
        ## => 내가 정의해야한다.
        ## => 함수로 정의해야 route에서 page를 stringquery변수로 받아올때 처리가 편하다
        ## => page는 1번부터 시작하게 한다.
        ## => 데이터가 없을 때는, 404에러를 내어야하는데, 지금은 []빈 데이터가 넘어가는 경우 아예 표시되지 않는다.
        ##   (for순회의 힘)
        # the page number, starting from 1
        # the number of items per page
        # an error flag. If True, when an out of range page is requested a 404 error will be automatically returned to the client. If False, an empty list will be returned for out of range pages.
        page = request.args.get('page', 1, type=int)
        # stmt = paginate(stmt, page=page, per_page=db_config.COMMENTS_PER_PAGE)
        # comments = db.session.scalars(stmt).all()
        # 1) comments객체 대신 pagination객체를 받아와서 -> comments key에 pagination.items를 넘겨준다
        comment_pagination = paginate(stmt, page=page, per_page=db_config.COMMENTS_PER_PAGE)

    # 2) prev_url, next_url 객체를 url_for()를 이용해 미리 만들어서 같이 넘겨준다.
    #   (만약 미리 만들지 않으면, view(html)에서 pagination객체를 받아 .속성을 이용해 url_for()를 만들어야 해서 복잡?)
    # => 여기서는 view에는 pagination객체 말고, entity객체와 url_for객체를 미리 만들어서 넘겨주자
    # 2-1) if .has_next 면 .next_num을 page=keyword에 넣어서 url_for객체를,
    #     아니면 None을 넣어서 next_url객체를 만든다.
    next_url = url_for('api_routes.explore', page=comment_pagination.next_num) \
        if comment_pagination.has_next else None
    prev_url = url_for('api_routes.explore', page=comment_pagination.prev_num) \
        if comment_pagination.has_prev else None

    with DBConnectionHandler() as db:
        stmt = (
            select(Comment)
            .where(Comment.id == 1)
        )
        comments2 = db.session.scalars(
            stmt
        ).all()

    # 3) 만들어준 pages + 현재page번호를 필드도 같이 넘겨준다.
    return render_template("menu/comment.html"
                           , comment_form=comment_form
                           , reply_form=reply_form
                           , comments=comment_pagination.items
                           , next_url=next_url
                           , prev_url=prev_url
                           , current_page=comment_pagination.page
                           , pages=comment_pagination.pages
                           , comments2=comments2
                           )


@api_routes_bp.route("/comments", methods=["GET", "POST"])
def index():
    comment_form = CommentForm()
    reply_form = ReplyForm()

    if request.method == 'POST' and comment_form.validate_on_submit():
        author = comment_form.author.data
        text = comment_form.text.data

        comment = Comment(text=text, author=author)
        comment.save()

        flash("comment posted", "success")

    with DBConnectionHandler() as db:
        stmt = (
            select(Comment)
            .options(lazyload('*'))  # 현재 lazy="subquery"y로 되어있기 때문에, jinja용 path이용한다면, 다 가져올 필요없음. flat 조회
            .order_by(Comment.thread_timestamp.desc(), Comment.level, Comment.timestamp.desc())
        # (특정최상위 선택안할시 그룹칼럼별), level별, 원하는 순서
        )
        page = request.args.get('page', 1, type=int)
        # stmt = paginate(stmt, page=page, per_page=db_config.COMMENTS_PER_PAGE)

        comment_pagination = paginate(stmt, page=page, per_page=db_config.COMMENTS_PER_PAGE)

        # comments2 = db.session.scalars(select(Comment).options(joinedload(Comment.replies)).where(Comment.id == 1)).all()
        # https://stackoverflow.com/questions/47243397/sqlalchemy-joinedload-filter-column

        # lazy='joined')
        stmt = (
            select(Comment)
            # .options(
            ## backref parent +  remoste_side가 없으면,
            # lazy=subquery + join_depth=6에
            # + select만으로 options없이 다됨.

            ## 한꺼번에 보내기 위해.relatinoship lazy dynamic -> 생략
            ## joinedload를 하면 on절 2개를 유추하나본다 ->  unique() method에러가 난다고 한다.
            ## subqueryload밖에 없는데 1번만하면, depth1만 지정하게 된다.
            ## selectin도 여러번 하면 가능 depth1만 지정하게 된다.
            # selectinload("replies")
            # FK에 uniquekey를 주고, joinedload는 unique() method에러는 안나나 ->( backref (parent-one)로 도전) => 여러개 걸어도 detach걸림
            # joinedload(Comment.replies, aliase=True)

            ## 찾았따.. (1) lazy로 subquery로 걸어놓고
            ##         (2) join_depth = 6 으로 주면, subquery든 selectinload든 1번만 걸어주면 자체참조 알아서 깊이만큼해준다.

            # selectinload("replies")
            # subqueryload("replies")
            ## 공식문서 마지막: https://docs.sqlalchemy.org/en/20/orm/self_referential.html#composite-adjacency-lists

            # .selectinload("replies")
            # .selectinload("replies")
            # .selectinload("replies")
            # .selectinload("replies")
            # .selectinload("replies")
            # .joinedload("parent")
            # .joinedload("parent")
            # .joinedload("parent")
            # .joinedload("parent")
            # .joinedload("parent")
            ## depth만큼 안해주면
            # .DetachedInstanceError: Parent instance
            # .selectinload("replies")
            # .selectinload("replies")
            # .selectinload("replies")
            # .selectinload("replies")
            # .subqueryload(Comment.replies)
            # .subqueryload(Comment.replies)
            # .subqueryload(Comment.replies)
            # .subqueryload(Comment.replies)
            # .subqueryload(Comment.replies)
            # )\
            .where(Comment.id == 1)
        )
        # print(stmt)

        comments2 = db.session.scalars(
            stmt
        ).all()
        # comments2 = db.session.scalars(select(Comment).options(joinedload(Comment.replies)).where(Comment.id == 1)).all()
        # comments2 = db.session.scalars(select(Comment).options(selectinload(Comment.replies)).where(Comment.id == 1)).all()
        # comments2 = db.session.scalars(select(Comment).options(subqueryload(Comment.replies)).where(Comment.id == 1)).all()
        # -> The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
        # -> The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
        # -> The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
        # -> The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections

        ## lazy='dynamic')
        # -> Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Comment.replies has an attribute '__name__'
        # -> 'Comment.replies' does not support object population - eager loading cannot be applied.
        # -> 'Comment.replies' does not support object population - eager loading cannot be applied.
        # -> 'Comment.replies' does not support object population - eager loading cannot be applied.

        ##
        # def is_parent(self):
        #     return self.parent_id == self.id
        # To obtain the siblings of an issue you can write a custom query that gets all the issues that have the same parent_id except the one the query is issued on:
        #
        # def get_siblings(self):
        #     return Issue.query.filter(Issue.parent_id == self.parent_id, Issue.id != self.id).all()

    # 2) prev_url, next_url 객체를 url_for()를 이용해 미리 만들어서 같이 넘겨준다.
    #   (만약 미리 만들지 않으면, view(html)에서 pagination객체를 받아 .속성을 이용해 url_for()를 만들어야 해서 복잡?)
    # => 여기서는 view에는 pagination객체 말고, entity객체와 url_for객체를 미리 만들어서 넘겨주자
    # 2-1) if .has_next 면 .next_num을 page=keyword에 넣어서 url_for객체를,
    #     아니면 None을 넣어서 next_url객체를 만든다.
    next_url = url_for('api_routes.index', page=comment_pagination.next_num) \
        if comment_pagination.has_next else None
    prev_url = url_for('api_routes.index', page=comment_pagination.prev_num) \
        if comment_pagination.has_prev else None

    # 3) 만들어준 pages + 현재page번호를 필드도 같이 넘겨준다.
    return render_template("menu/comment.html", comments=comment_pagination.items, comments2=comments2
                           , comment_form=comment_form
                           , reply_form=reply_form
                           , next_url=next_url
                           , prev_url=prev_url
                           , current_page=comment_pagination.page
                           , pages=comment_pagination.pages
                           )


@api_routes_bp.route("/comments/<int:comment_id>", methods=["POST"])  # ,strict_slashes=False)
def register_reply(comment_id):
    reply_form = ReplyForm()

    if request.method == 'POST' and reply_form.validate_on_submit():
        author = reply_form.author.data
        text = reply_form.text.data

        # comment = Comment(text=text, author=author)
        with DBConnectionHandler() as db:
            stmt = (
                select(Comment)

src/main/routes/util_route.py
from flask import request, url_for, Blueprint

from src.main.decorators.decorators import login_required
from src.main.utils import upload_file_path

util_bp = Blueprint("util", __name__, url_prefix='/util')


# upload route
# 1. POST로 FormData를 받긴 하지만, upload요청마다 '/uploads/`폴더 속 `개별디렉토리이름`은 요청마다 달라진다.
# -> POST지만, path로 directory_name을 받아서, 업로드폴더의 하위 개별폴더로 지정해서 저장하도록 한다

@util_bp.route('/upload/<path:directory_name>', methods=['POST'])
@login_required
def upload(directory_name):
    if request.method == 'POST':
        # 2. 파일객체는 new FormData()객체 속 'upload'로 append했는데
        # -> request.files.get('upload')로 받아낼 수 있다.
        f = request.files.get('upload')
        # 3. file객체를 .read()로 내용물을 읽고 file size를 젠 뒤
        # -> file객체의 읽은 위치를 다시 처음으로 초기화해놓는다.(읽고 커서가 뒤로 갔지만, 다시 원위치
        file_size = len(f.read())
        f.seek(0)
        # 4. 업로드 파일 사이즈를 체크한다. form에서는 validators= [FileSize(max_size=2048000))]으로 해결
        # -> 사이즈가 넘어가면 alert를 띄울 수있게 message를 같이 전달한다.
        if file_size > 2048000:
            return {
                'code': 'err',
                'message': '파일크기가 2M를 넘을 수 없습니다.'
            }
        # 5. upload유틸을 이용해서, '/uploads/`폴더에 붙을 '개별디렉토리', file객체를 넣어주면
        # -> save할 path와 filename이 주어진다.
        # -> 그렇다면, front에서 upload할 개별디렉토리도 보내줘야한다?!
        upload_path, filename = upload_file_path(directory_name=directory_name, file=f)
        # print(upload_path, filename)
        # C:\Users\is2js\pythonProject\2022_sqlalchemy\uploads\post\28d12f83306f4bf6984c9b6bcef7dda5.png 28d12f83306f4bf6984c9b6bcef7dda5.png

        # 6. 저장 후 ok return 시  jsonify없이 그냥 dict로 반환한다?
        # -> 반환시 view에서 볼 img저장경로를 넘겨줘야, 거기서 표시할 수 있을 것이다.
        f.save(upload_path)
        # print(url_for('download_file', filename=f'{directory_name}/{filename}'))
        # /uploads/post/862e406dd33a48b6aed55e64e68586ff.png

        return {
            'code': 'ok',
            # 'url': f'/uploads/{directory_name}/{filename}',
            'url': url_for('download_file', filename=f'{directory_name}/{filename}'),
        }

src/main/templates/filters/__init__.py
from .feed_datetime import feed_datetime
from .join_phone import join_phone, join_birth

src/main/utils/__init__.py
from .upload_utils import upload_file_path, delete_uploaded_file, delete_files_in_img_tag
from .utils import remove_empty_and_hyphen, redirect_url

src/main/templates/menu/article.html
{% extends 'base.html'%}
{% block content%}
<div class="container row">
    <div class="shadow p-4 mb-4 col-lg-12 col-sm-6">
        <h3>{{post.title}}</h3>
        <br>
        <p>{{post.body}}</p>
        <hr>
        <form action="{{request.path }}" method="POST">
            {{ form1.csrf_token }}
            <div class="form-group mt-2">
                {{form1.author(class="form-control", placeholder="Author")}}
            </div>
            <div class="form-group mt-2">
                {{form1.comment(class="form-control" ,placeholder="Comment")}}
            </div>
            <button type="submit" class="btn btn-primary mt-2">Post comment</button>
        </form>
    </div>
    <div class="shadow-sm p-4 col-lg-12 col-sm-6">
        {% for comment in comments %}
        <div class="row">
            <!-- Begin comment indentation -->
            {% if comment.level() == 0 %}
            <div class="col-12 border-start border-primary">
                {% elif comment.level() == 1 %}
                <div class="col-11 offset-1 border-start border-secondary">
                    {% elif comment.level() == 2 %}
                    <div class="col-10 offset-2 border-start border-success">
                        {% elif comment.level() == 3 %}
                        <div class="col-9 offset-3 border-start border-info">
                            {% elif comment.level() == 4 %}
                            <div class="col-8 offset-4 border-start border-primary">
                                {% else %}
                                <div class="col-7 offset-5 border-start border-primary">
                                    {% endif %}
                                    <!-- End comment indentation -->
                                    <div>
                                        <p class="m-0">{{comment.author}}</p>
                                        <p class="m-0">{{comment.text}}</p>
                                        <a class="" data-bs-toggle="collapse" href="#comment-{{comment.id}}"
                                           role="button" aria-expanded="false" aria-controls="collapseExample">
                                            <i class="bi bi-reply"></i>
                                        </a>
                                    </div>
                                    <div class="collapse w-50" id="comment-{{comment.id}}">
                                        <form action="{{url_for('reply_comment',post_id=post.id,comment_id=comment.id) }}"
                                              method="POST">
                                            {{ form2.csrf_token }}
                                            <div class="form-group mt-2">
                                                {{form2.author(class="form-control", placeholder="Name")}}
                                            </div>
                                            <div class="form-group mt-2">
                                                {{form2.reply(class="form-control" ,placeholder="Response")}}
                                            </div>
                                            <button type="submit" class="btn btn-primary mt-2 btn-sm">Post Reply
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endblock%}

src/main/templates/menu/comment.html
{% extends 'menu/base.html'%}
{% block content%}
<div class="container row">
    <div class="shadow-sm p-4 col-lg-12 col-sm-6">
        <!-- COMMENT POST       -->
        <div class="shadow p-4 mb-4 col-lg-12 col-sm-6">
            <form action="{{url_for('api_routes.index') }}" method="POST">
                {{ comment_form.csrf_token }}
                <div class="form-group mt-2">
                    {{comment_form.author(class="form-control", placeholder="Author")}}
                </div>
                <div class="form-group mt-2">
                    {{comment_form.text(class="form-control", placeholder="Comment")}}
                </div>
                <button type="submit" class="btn btn-primary mt-2">Post comment</button>
                전체 댓글 수 : {{ comments | length }}
            </form>
        </div>


        <!--  COMMENT SELECT and REPLY POST     -->
        <div class="shadow-sm p-4 col-lg-12 col-sm-6">
            <!--  COMMENT pagination     -->
            <div class="text-center mb-3">
                <!--  이전 페이지가 있으면, 이전url객체 + 아이콘     -->
                {% if prev_url %}
                    <a href="{{ prev_url }}"><i class="fs-5 bi bi-caret-left-fill danger" ></i></a>
                {% endif %}

                <!--  전체페이지 중에 가운데 숫자 current_page와 차이 2개까지 표시     -->
                {% for number in range(1, pages) %}
                    {% if ((number - current_page) | abs)  <= 2 %}
                        {% if number == current_page %}
                        <span class=" fs-2 fw-bold danger">{{ number }}</span>
                        {% else %}
                        <span > <a class="default" href="{{url_for('api_routes.index', page=number)}}" style="text-decoration: none;">{{ number }}</a></span>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                <!--  다음 페이지가 있으면, 다음url객체 + 아이콘     -->
                {% if next_url %}
                    <a href="{{ next_url }}"><i class="fs-5 bi bi-caret-right-fill danger"></i></a>
                {% endif %}
            </div>


            {% for comment in comments %}
            <!--  design 1 : dynamic -> flat but level() 존재 -> view에서 level값으로 확인. 해당 post_id가 들어간 것 다 조회 -> lazy 면 됨. but flat하지만 level()로 알아차림.       -->
            <div class="row">
                <!-- Begin comment indentation -->
                <div class="
                col-{{12 - comment.level}} offset-{{comment.level}}
                 {{ 'border-1 ' if comment.level == 0 else 'border-1' }} border-muted py-1
                comment-body {{'comment-body-odds' if loop.index  %2 == 1}}
                ">
                    <!-- End comment indentation -->
                    <div>
                        <p class="my-1">
                            <span class="label label-default">#{{comment.id}}</span>
                            <span class="label {{ 'label-danger' if comment.author == '돌범' else 'label-primary'}}"> {{comment.author}}</span>
                            <span class="label text-muted">{{comment.timestamp | feed_datetime(is_feed=True)}}</span>
                        </p>
                        <!-- 필터 만들고 싶다면: https://sooooooyn.tistory.com/4?category=863481-->
                        <p class="my-2">{{comment.text}} <a href="{{url_for('api_routes.delete_comment', comment_id=comment.id)}}" class="bi bi-x-square danger"></a></p>

                        <!-- 특정level이상부터는 못달게 작성부분을 if문 걸어보기-->
                        {% if comment.level < 6 %}
                        <!--[1] 대댓글 아이콘i태그를 a태그에 감싼다. -->
                        <!--(1) a태그에 data-bs-toggle="collapse" 속성 + role="button" 속성 -->
                        <!--(2) a태그에 href ="#나타날 공간이 받을 id"  -->
                        <a class="" data-bs-toggle="collapse" href="#comment-{{comment.id}}"
                           role="button" aria-expanded="false" aria-controls="collapseExample">
                            {% if comment.level < 1 %}
                            <i class="bi bi-chat-left-dots" style="color:gray"></i>
                            {% else %}
                            <i class="bi bi-reply" style="color:gray"></i>
                            {% endif %}
                        </a>
                        {% else %}
                        <i class="bi-reply"></i>
                        {% endif %}
                    </div>
                    <!--[2] 대댓글 form이 나타날 공간 div -->
                    <!--(1) class="collapse w-50" 속성 -->
                    <!--(2) id="{컬랩스트리거 a태그의 href속성값에서 #을 뺀 문자열}" -->
                    <div class="collapse w-50" id="comment-{{comment.id}}">
                        <form action="{{url_for('api_routes.register_reply', comment_id=comment.id) }}" method="POST">
                            {{ reply_form.csrf_token }}
                            <div class="form-group mt-2">
                                {{reply_form.author(class="form-control", placeholder="Author")}}
                            </div>
                            <div class="form-group mt-2">
                                {{reply_form.text(class="form-control" ,placeholder="Comment")}}
                            </div>
                            <button type="submit" class="btn btn-primary mt-2 btn-sm">Post Reply</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}

            <!-- design 2 : comment 1개를 조회하면, 필드에 다 하위댓글들 다 품고 조회      -->
            <!-- path + level이 필요없이, view에선 계층적구조 -> 재귀로 level별 출력       -->
            {% for comment in comments2 recursive %}
            <li>{{ comment.text }} by {{ comment.author}}</li>
            <!-- 없어도 될듯. 존재할때만 collection에 담겨 순회 for-->
            {% if comment.replies %}
            <ul class="children">{{loop(comment.replies)}}</ul>
            {% endif %}
            {% endfor %}

        </div>
    </div>
</div>
</div>
{% endblock%}